### ISSUE TITLE
Install script does not pull from docker registrey

### ISSUE THREAD

**Issue by danielo515** [D-Nice/vindi#15]
Taking a look at the install script I don't see any part of it where you download the built image from the docker registry. So the first prompt actually means "you want to make this script fail or not?"

Regards

**Comment by danielo515** [comment]
Ok, I see that the image is selected on the binary section.
But then, if you answer no to both questions you will end with nothing changed.
Would'n be easier to just say "if you don't want to install vindi, just run bin/vindi script" or something like that?

Regards

**Comment by danielo515** [comment]
I re-read the readme and I think it is not clear for people like me, but it is probably clear for everyone else, so forget about what I said.
In any case, I just copy pasted the docker command on the bin folder and that was more than enough to give vindi a try, so it is worth giving that option to those who do not want to download the repository to just give it a try.

Thanks for this project!

**Comment by D-Nice** [comment]
Yes, apologies, it may not be the most intuitive, the "binary" script will pull the image for you, if you don't already have a local `vindi` image you may have built yourself. Your local image will always take precedence.

**Comment by D-Nice** [comment]
To summarize, you don't need to pull the image yourself.

On a new pc just now, I got vindi working by...

1. Running install script, and choosing no when it asks to build, but yes, when it asks to install the vindi "binary" (quotation marks, because it's a shell script you can verify and read). 
2. then running vindi, since this PC did not have any vindi instance on it, the binary on its own pulls the image for you. You are of course free to manually pull, there are many steps.

Still, thank you for the feedback, I may work to clarify the steps some more so they're more easily understandable, I strive for it to be as simple and turnkey as possible, whether for a developer, hobbyist, etc...
